const sampleData = [
  {
    name: "Classic Oyster Grow Kit",
    description: "Complete starter kit with pre-colonized substrate and humidity tent. Yields up to 2kg.",
    price: 1500,
    category: "Kit",
    type: "produce",
    image: "/uploads/mush-11.jpg",
    rating: 5,
    stock: 100,
    isAvailable: true
  },
  {
    name: "Golden Teacher Spore Syringe",
    description: "For microscopy use only. Premium quality spores in a sterile 10cc syringe.",
    price: 25,
    category: "Supplies",
    type: "produce",
    image: "/uploads/mush-12.jpg",
    rating: 4.9,
    stock: 500,
    isAvailable: true
  },
  {
    name: "Lion's Mane Liquid Culture",
    description: "Premium isolated genetics in a 10cc sterile syringe. Ready to inoculate.",
    price: 35,
    category: "Supplies",
    type: "produce",
    image: "/uploads/mush-13.jpg",
    rating: 5,
    stock: 250,
    isAvailable: true
  },
  {
    name: "Sterilized Grain Bags (3lbs)",
    description: "Rye berry spawn bags with self-healing injection ports. Perfect for home growers.",
    price: 22,
    category: "Supplies",
    type: "produce",
    image: "/uploads/mush-11.jpg",
    measures: ["1 Bag", "3 Bags"],
    prices: { "1 Bag": 22, "3 Bags": 60 },
    rating: 4.9,
    stock: 150,
    isAvailable: true
  },
  {
    name: "CVG Bulk Substrate (5lbs)",
    description: "Pasteurized Coco Coir, Vermiculite, and Gypsum mix. Ready to fruit.",
    price: 35,
    category: "Supplies",
    type: "produce",
    image: "/uploads/mush-14.jpg",
    measures: ["5lbs", "10lbs"],
    prices: { "5lbs": 35, "10lbs": 65 },
    rating: 4.8,
    stock: 200,
    isAvailable: true
  },
  {
    name: "Mushroom Spawn (Seeds)",
    description: "High quality mycelium spawn for various mushroom strains. Perfect for bulk inoculation.",
    price: 15,
    category: "Supplies",
    type: "produce",
    image: "/uploads/mush-11.jpg",
    rating: 4.8,
    stock: 500,
    isAvailable: true
  },
  {
    name: "Paddy Straw / Wheat Straw",
    description: "Clean, dry straw substrate ideal for growing oyster mushrooms.",
    price: 10,
    category: "Supplies",
    type: "produce",
    image: "/uploads/mush-12.jpg",
    measures: ["1kg", "5kg", "20kg"],
    prices: { "1kg": 10, "5kg": 40, "20kg": 120 },
    rating: 4.7,
    stock: 1000,
    isAvailable: true
  },
  {
    name: "Mushroom Growing Bags (Poly Bags)",
    description: "Heat-resistant polypropylene bags with breathable filter patches for gas exchange.",
    price: 18,
    category: "Supplies",
    type: "produce",
    image: "/uploads/mush-13.jpg",
    measures: ["50 Pack", "100 Pack"],
    prices: { "50 Pack": 18, "100 Pack": 30 },
    rating: 4.9,
    stock: 300,
    isAvailable: true
  },
  {
    name: "Substrate (Compost / Sawdust)",
    description: "Pre-mixed hardwood sawdust or compost substrate directly formulated for wood-loving mushrooms.",
    price: 20,
    category: "Supplies",
    type: "produce",
    image: "/uploads/mush-14.jpg",
    measures: ["5lbs", "10lbs"],
    prices: { "5lbs": 20, "10lbs": 35 },
    rating: 4.8,
    stock: 200,
    isAvailable: true
  },
  {
    name: "Mushroom Racks / Shelves",
    description: "Durable, rust-resistant shelving units for organizing your grow bags and trays.",
    price: 85,
    category: "Equipment",
    type: "produce",
    image: "/uploads/mush-11.jpg",
    rating: 4.6,
    stock: 50,
    isAvailable: true
  },
  {
    name: "Humidity Sprayer",
    description: "Automated timed humidity sprayer to maintain optimal growing environment.",
    price: 45,
    category: "Equipment",
    type: "produce",
    image: "/uploads/mush-12.jpg",
    rating: 4.8,
    stock: 100,
    isAvailable: true
  },
  {
    name: "Temperature and Humidity Meter",
    description: "Digital hygrometer and thermometer for precise climate monitoring.",
    price: 12,
    category: "Equipment",
    type: "produce",
    image: "/uploads/mush-13.jpg",
    rating: 4.9,
    stock: 200,
    isAvailable: true
  },
  {
    name: "Water Spray Bottle",
    description: "Ultra-fine continuous mist spray bottle for manual surface hydration.",
    price: 8,
    category: "Equipment",
    type: "produce",
    image: "/uploads/mush-14.jpg",
    rating: 4.7,
    stock: 300,
    isAvailable: true
  },
  {
    name: "Disinfectant / Formalin Solution",
    description: "Sterilization solution for cleaning grow rooms, tools, and surfaces.",
    price: 15,
    category: "Supplies",
    type: "produce",
    image: "/uploads/mush-11.jpg",
    rating: 4.8,
    stock: 150,
    isAvailable: true
  },
  {
    name: "Hand Gloves and Face Mask",
    description: "Sterile personal protective equipment to prevent contamination.",
    price: 5,
    category: "Supplies",
    type: "produce",
    image: "/uploads/mush-12.jpg",
    measures: ["5 Pairs", "50 Box"],
    prices: { "5 Pairs": 5, "50 Box": 35 },
    rating: 4.9,
    stock: 400,
    isAvailable: true
  },
  {
    name: "Mushroom Drying Tray",
    description: "Mesh trays for sun-drying or dehydrating your harvested mushrooms safely.",
    price: 22,
    category: "Equipment",
    type: "produce",
    image: "/uploads/mush-13.jpg",
    rating: 4.5,
    stock: 80,
    isAvailable: true
  },
  {
    name: "Plastic Crates for Harvesting",
    description: "Vented plastic harvesting crates for transporting fresh mushrooms without bruising.",
    price: 14,
    category: "Equipment",
    type: "produce",
    image: "/uploads/mush-14.jpg",
    rating: 4.6,
    stock: 120,
    isAvailable: true
  },
  {
    name: "Mushroom Packing Covers",
    description: "Breathable plastic retail covers for packaging fresh mushrooms for sale.",
    price: 10,
    category: "Supplies",
    type: "produce",
    image: "/uploads/mush-11.jpg",
    measures: ["100 Pack", "500 Pack"],
    prices: { "100 Pack": 10, "500 Pack": 40 },
    rating: 4.8,
    stock: 250,
    isAvailable: true
  },
  {
    name: "Shade Net / Mushroom Growing Tent",
    description: "Agricultural shade nets to build insulated and dark fruiting chambers.",
    price: 65,
    category: "Equipment",
    type: "produce",
    image: "/uploads/mush-12.jpg",
    rating: 4.7,
    stock: 40,
    isAvailable: true
  }
];

module.exports = sampleData;
