const sampleData = [
  {
    name: "Classic Oyster Grow Kit",
    description: "Complete starter kit with pre-colonized substrate and humidity tent. Yields up to 2kg.",
    price: 1500,
    category: "Kit",
    type: "produce",
    image: "/uploads/mush-11.jpg",
    rating: 5,
    stock: 100,
    isAvailable: true
  },
  // Fresh oyster products
  {
    name: "Fresh Oyster - 250g",
    description: "Freshly harvested oyster mushrooms — packed and ready for sale. Grown locally with care.",
    price: 199,
    category: "Oyster",
    type: "produce",
    image: "/uploads/mush-14.jpg",
    rating: 4.8,
    stock: 120,
    isAvailable: true
  },
  {
    name: "Fresh Oyster - 500g",
    description: "Half-kilo pack of fresh oyster mushrooms — ideal for restaurants and bulk buyers.",
    price: 349,
    category: "Oyster",
    type: "produce",
    image: "/uploads/mush-13.jpg",
    rating: 4.9,
    stock: 80,
    isAvailable: true
  },
  {
    name: "Fresh Oyster - Mixed Pack (250g x 2)",
    description: "Two 250g packs in one mixed bundle — great value and freshness guaranteed.",
    price: 349,
    category: "Oyster",
    type: "produce",
    image: "/uploads/mush-12.jpg",
    rating: 4.9,
    stock: 60,
    isAvailable: true
  },
  {
    name: "Golden Teacher Spore Syringe",
    description: "Sterile 10cc syringe prepared for clean inoculation workflows. Sealed packaging and easy handling.",
    price: 499,
    category: "Supplies",
    type: "produce",
    image: "/uploads/mush-12.jpg",
    rating: 4.9,
    stock: 500,
    isAvailable: true
  },
  {
    name: "Lion's Mane Liquid Culture",
    description: "Active liquid culture in a sterile syringe for quick inoculation. Designed for clean handling and consistent results.",
    price: 549,
    category: "Supplies",
    type: "produce",
    image: "/uploads/mush-13.jpg",
    rating: 5,
    stock: 250,
    isAvailable: true
  },
  {
    name: "Sterilized Grain Bags (3lbs)",
    description: "Sterilized grain bag with injection port and filter patch for easy inoculation and strong colonization. Great for home setups.",
    price: 399,
    category: "Supplies",
    type: "produce",
    image: "/uploads/mush-11.jpg",
    measures: ["1 Bag", "3 Bags"],
    prices: { "1 Bag": 399, "3 Bags": 999 },
    rating: 4.9,
    stock: 150,
    isAvailable: true
  },
  {
    name: "CVG Bulk Substrate (5lbs)",
    description: "Ready-to-use substrate mix for fruiting and bulk grows. Balanced moisture performance and consistent texture for cultivation.",
    price: 449,
    category: "Supplies",
    type: "produce",
    image: "/uploads/mush-14.jpg",
    measures: ["5lbs", "10lbs"],
    prices: { "5lbs": 449, "10lbs": 799 },
    rating: 4.8,
    stock: 200,
    isAvailable: true
  },
  {
    name: "Mushroom Spawn (Seeds)",
    description: "High quality mycelium spawn for various mushroom strains. Perfect for bulk inoculation.",
    price: 299,
    category: "Supplies",
    type: "produce",
    image: "/uploads/mush-11.jpg",
    rating: 4.8,
    stock: 500,
    isAvailable: true
  },
  {
    name: "Paddy Straw / Wheat Straw",
    description: "Clean, dry straw substrate ideal for growing oyster mushrooms.",
    price: 199,
    category: "Supplies",
    type: "produce",
    image: "/uploads/mush-12.jpg",
    measures: ["1kg", "5kg", "20kg"],
    prices: { "1kg": 199, "5kg": 699, "20kg": 1999 },
    rating: 4.7,
    stock: 1000,
    isAvailable: true
  },
  {
    name: "Mushroom Growing Bags (Poly Bags)",
    description: "Heat-resistant polypropylene bags with breathable filter patches for gas exchange.",
    price: 299,
    category: "Supplies",
    type: "produce",
    image: "/uploads/mush-13.jpg",
    measures: ["50 Pack", "100 Pack"],
    prices: { "50 Pack": 299, "100 Pack": 449 },
    rating: 4.9,
    stock: 300,
    isAvailable: true
  },
  {
    name: "Substrate (Compost / Sawdust)",
    description: "Pre-mixed hardwood sawdust or compost substrate directly formulated for wood-loving mushrooms.",
    price: 399,
    category: "Supplies",
    type: "produce",
    image: "/uploads/mush-14.jpg",
    measures: ["5lbs", "10lbs"],
    prices: { "5lbs": 399, "10lbs": 699 },
    rating: 4.8,
    stock: 200,
    isAvailable: true
  },
  {
    name: "Mushroom Racks / Shelves",
    description: "Durable, rust-resistant shelving units for organizing your grow bags and trays.",
    price: 2999,
    category: "Equipment",
    type: "produce",
    image: "/uploads/mush-11.jpg",
    rating: 4.6,
    stock: 50,
    isAvailable: true
  },
  {
    name: "Humidity Sprayer",
    description: "Automated timed humidity sprayer to maintain optimal growing environment.",
    price: 1499,
    category: "Equipment",
    type: "produce",
    image: "/uploads/mush-12.jpg",
    rating: 4.8,
    stock: 100,
    isAvailable: true
  },
  {
    name: "Temperature and Humidity Meter",
    description: "Digital hygrometer and thermometer for precise climate monitoring.",
    price: 399,
    category: "Equipment",
    type: "produce",
    image: "/uploads/mush-13.jpg",
    rating: 4.9,
    stock: 200,
    isAvailable: true
  },
  {
    name: "Water Spray Bottle",
    description: "Ultra-fine continuous mist spray bottle for manual surface hydration.",
    price: 199,
    category: "Equipment",
    type: "produce",
    image: "/uploads/mush-14.jpg",
    rating: 4.7,
    stock: 300,
    isAvailable: true
  },
  {
    name: "Disinfectant / Formalin Solution",
    description: "Sterilization solution for cleaning grow rooms, tools, and surfaces.",
    price: 249,
    category: "Supplies",
    type: "produce",
    image: "/uploads/mush-11.jpg",
    rating: 4.8,
    stock: 150,
    isAvailable: true
  },
  {
    name: "Hand Gloves and Face Mask",
    description: "Sterile personal protective equipment to prevent contamination.",
    price: 199,
    category: "Supplies",
    type: "produce",
    image: "/uploads/mush-12.jpg",
    measures: ["5 Pairs", "50 Box"],
    prices: { "5 Pairs": 199, "50 Box": 699 },
    rating: 4.9,
    stock: 400,
    isAvailable: true
  },
  {
    name: "Mushroom Drying Tray",
    description: "Mesh trays for sun-drying or dehydrating your harvested mushrooms safely.",
    price: 699,
    category: "Equipment",
    type: "produce",
    image: "/uploads/mush-13.jpg",
    rating: 4.5,
    stock: 80,
    isAvailable: true
  },
  {
    name: "Plastic Crates for Harvesting",
    description: "Vented plastic harvesting crates for transporting fresh mushrooms without bruising.",
    price: 499,
    category: "Equipment",
    type: "produce",
    image: "/uploads/mush-14.jpg",
    rating: 4.6,
    stock: 120,
    isAvailable: true
  },
  {
    name: "Mushroom Packing Covers",
    description: "Breathable plastic retail covers for packaging fresh mushrooms for sale.",
    price: 299,
    category: "Supplies",
    type: "produce",
    image: "/uploads/mush-11.jpg",
    measures: ["100 Pack", "500 Pack"],
    prices: { "100 Pack": 299, "500 Pack": 999 },
    rating: 4.8,
    stock: 250,
    isAvailable: true
  },
  {
    name: "Shade Net / Mushroom Growing Tent",
    description: "Agricultural shade nets to build insulated and dark fruiting chambers.",
    price: 1999,
    category: "Equipment",
    type: "produce",
    image: "/uploads/mush-12.jpg",
    rating: 4.7,
    stock: 40,
    isAvailable: true
  }
];

module.exports = sampleData;
